### PR TITLE
Added test to verify the url of the fact sheet

### PR DESCRIPTION
**Pull request by alinai**
Added test to verify the url of the FactSheet List Page. Please approve. Thanks!

### CODE REVIEW

**Review by blairlearn — CHANGES_REQUESTED** [review]
Do not test that the url is exactly equal to anything containing a host name.  (i.e. don't compare to "https://www-qa.can....").

Instead, use the PageUrl object returned from the page object's GetPageUrl() method (I think that's the name) and compare (a) The path portion and (b) any expected query parameters.

**Comment by alinai** [comment]
Rebased to sync with the Sprint branch (Automation-12-05) and updated the test to compare the path portion of the url (OCEPROJECT-4842).

**Comment by alinai** [comment]
Used the page object's GetPageUrl() method to compare the path. OCEPROJECT-4842.

**Review by blairlearn — APPROVED** [review]

**Comment by alinai** [comment]
OCEPROJECT-4842 branch has been updated from the Sprint branch Automation-12-05

**Pull request merged**
