### PR TITLE
GlossaryES - Test that widget link goes to widget page. OCEPROJECT-4796

### PR DESCRIPTION
**Pull request by venglisch**

### CODE REVIEW

**Review by blairlearn — CHANGES_REQUESTED** [review]
The `DictionarySearch.linksToWidgetPage()` method should have a single responsibility. It should not click the link and then determine whether the test has passed.

A possible rewrite -- a method in `DictionarySearch` which click the link and return a page object (containing the result of the click).  The returned page object is of a class which implements a method for retrieving the link text.

**Comment by venglisch** [comment]
I had the feeling you might say this but I thought your approach would complicate a simple method unnecessarily.
I'll take a look at rewriting it to the Blair-way.

**Comment by blairlearn** [comment]
A reason for "the Blair-way" is it leaves you with a method on the page object for retrieving the page associated with a given link. Future tests can then use that same method to evaluate various aspects of the resulting page without needing to modify the `DictionarySearch` class.

**Comment by venglisch** [comment]
Pull request closed. A new pull request will be submitted based on the "automation-12-05" branch.

**Pull request closed without merging**
