### PR TITLE
Drug Test if letter A results is home page. OCEPROJECT-4932

### PR DESCRIPTION
**Pull request by venglisch**

### CODE REVIEW

**Review by blairlearn — COMMENTED** [review]
@venglisch - This appears to be a test for the number of results returned for a single letter.  Is there a reason the the test method can't be parameterized to check for results for several different letters? (The actual letters would then, of course, be loaded from a data file.)

**Comment by venglisch** [comment]
We're actually not looking for the specific number of results returned.  The test is to identify that the page contains 1+ results and I'm checking for the existence of an integer value.
This test is checking to confirm that the "home page" for the dictionary is identical to the "letter A" page, so checking for any other letter would not make sense here.

**Comment by blairlearn** [comment]
Ah. I didn't understand that at first. (A downside to checking these things in bulk.)

Please rebase from the feature branch and resubmit.

**Comment by venglisch** [comment]
This PR has been replaced by #229. 
Deleting PR.

**Pull request closed without merging**
