### PR TITLE
Oceproject 4845

### PR DESCRIPTION
**Pull request by alinai**
Please approve. Thanks!

### CODE REVIEW

**Review by blairlearn — COMMENTED** [review]
Is this the same as #190 ??

**Comment by alinai** [comment]
No, it has one more test for Intro Text.

**Comment by alinai** [comment]
Submitted pull request https://github.com/NCIOCPL/wcms-qa-testing-framework/pull/195. A new test for verifying the Description Text has been added to the branch OCEPROJECT-4845 (#195).

**Comment by blairlearn** [comment]
This is an old pull request.  @alinai will create a new one against the `automation-12-05` branch.

**Pull request closed without merging**
